SiteOfClothing/Entities/ProductTypes/Shoes/SizeOfShoe.cs
using SiteOfShoes.Entities.Products.Shoes;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SiteOfShoes.Entities.ProductTypes.Shoes
{
    public class SizeOfShoe
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual List<Shoe> Shoes { get; set; } = new List<Shoe>();

    }
}

SiteOfClothing/Entities/ProductTypes/Shoes/TypeOfDestination.cs
using SiteOfShoes.Entities.Products.Shoes;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SiteOfShoes.Entities.ProductTypes.Shoes
{
    public class TypeOfDestination
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual List<Shoe> Shoes { get; set; } = new List<Shoe>();
    }
}

SiteOfClothing/Entities/ProductTypes/Shoes/TypeOfSeason.cs
using SiteOfShoes.Entities.Products.Shoes;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SiteOfShoes.Entities.ProductTypes.Shoes
{
    public class TypeOfSeason
    {

        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual List<Shoe> Shoes { get; set; } = new List<Shoe>();
    }
}

SiteOfClothing/Entities/ProductTypes/Shoes/TypeOfSex.cs
using SiteOfShoes.Entities.Products.Shoes;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SiteOfShoes.Entities.ProductTypes.Shoes
{
    public class TypeOfSex
    {

        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual List<Shoe> Shoes { get; set; } = new List<Shoe>();
    }
}

SiteOfClothing/Entities/ProductTypes/Shoes/TypeOfShoe.cs
using SiteOfShoes.Entities.Products.Shoes;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SiteOfShoes.Entities.ProductTypes.Shoes
{
    public class TypeOfShoe
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual List<Shoe> Shoes { get; set; } = new List<Shoe>();
    }
}

SiteOfClothing/Entities/Products/Shoes/Shoe.cs
using Arch.EntityFrameworkCore.UnitOfWork;
using SiteOfShoes.Entities.Ordering.Cart;
using SiteOfShoes.Entities.ProductTypes.Shoes;
using SiteOfShoes.Models.Products;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace SiteOfShoes.Entities.Products.Shoes
{
    public class Shoe : Product
    {
        public virtual List<Cart> Carts { get; set; } = new List<Cart>();


        public Shoe()
        {
        }

        public string Material { get; set; }

        [Required]

        public virtual TypeOfShoe TypeOfShoe { get; set; }

        public int? TypeOfShoeId { get; set; }

        [Required]

        public virtual TypeOfSeason TypeOfSeason { get; set; }

        public int? TypeOfSeasonId { get; set; }

        [Required]
        public virtual TypeOfSex TypeOfSex { get; set; }

        public int? TypeOfSexId { get; set; }

        public virtual TypeOfDestination TypeOfDestination { get; set; }

        public int? TypeOfDestinationId { get; set; }

        public string Color { get; set; }


        public void UpdateByShoeModel(ShoeModel model, IUnitOfWork unityOfWork)
        {
            Name = model.Name;
            isSaled = model.isSaled;
            SalePercent = model.SalePercent;
            Manufacturer = model.Manufacturer;
            Description = model.Description;
            PhotoLink = model.PhotoLink;
            Material = model.Material;
            SizesOfShoe = unityOfWork.GetRepository<SizeOfShoe>().GetAll().Where(t => model.SizesOfShoeIds.Contains(t.Id)).ToList();
            TypeOfDestinationId = model.TypeOfDestinationId;
            TypeOfSeasonId = model.TypeOfSeasonId;
            TypeOfSexId = model.TypeOfSexId;
            TypeOfShoeId = model.TypeOfShoeId;
            TypeOfDestination = model.TypeOfDestination;
            TypeOfSeason = model.TypeOfSeason;
            TypeOfSex = model.TypeOfSex;
            TypeOfShoe = model.TypeOfShoe;
            Color = model.Color;
        }
    }
}

SiteOfClothing/Controllers/CatalogController.cs
using Arch.EntityFrameworkCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SiteOfShoes.Entities.Accounting;
using SiteOfShoes.Entities.Products.Shoes;
using SiteOfShoes.Entities.ProductTypes.Shoes;
using System.Linq;
using SiteOfShoes.Models.Products;
using System.Collections.Generic;
using SiteOfShoes.Entities.Products;
using Data.EF;

namespace SiteOfShoes.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CatalogController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShoeTypes()
        {
            var types = _unitOfWork.GetRepository<TypeOfShoe>().GetAll();
            return View(types);
        }
        public IActionResult Catalog()
        {
            var items = _unitOfWork.GetRepository<Product>().GetAll()
                .Where(u => u.IsDeleted == false);
            return View(items);
        }

        public IActionResult ShoeCatalog(string type)
        {
            var items = _unitOfWork.GetRepository<TypeOfShoe>().GetAll()
                .Where(u => u.Name == type).FirstOrDefault();
            return View(items);
        }
    }
}

SiteOfClothing/Controllers/OrderController.cs
using Arch.EntityFrameworkCore.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteOfShoes.Entities.Accounting;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using SiteOfShoes.Entities.Products.Shoes;
using SiteOfShoes.Entities.Ordering.Cart;
using SiteOfShoes.Entities.ProductTypes.Shoes;
using SiteOfShoes.Entities.Ordering;
using SiteOfShoes.Entities.Products;

namespace WebUI.Controllers
{
    [Authorize]
    public class OrderingController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public OrderingController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        #region Orders
        [HttpGet]
        public ActionResult AddOrder()
        {
            var currentUser = _unitOfWork.GetRepository<User>().GetAll()
                .Where(user => user.Email == User.Identity.Name).FirstOrDefault();
            var orderRepo = _unitOfWork.GetRepository<Order>();
            var orderItemsRepo = _unitOfWork.GetRepository<OrderItem>();
            var productRepo = _unitOfWork.GetRepository<Product>();
            var cart = _unitOfWork.GetRepository<Cart>().GetAll().AsEnumerable()
                .Where(c => c.User.ID == currentUser.ID).FirstOrDefault();
            var order = new Order() { User = currentUser, UserId = currentUser.ID, Cost = cart.GetSum() };

            foreach (var cartItem in cart.CartItems)
            {
                var product = (Product)cartItem.Product;
                var orderItem = new OrderItem() { Order = order, Product = product, Cost = product.Costs[product.Costs.Count-1].Cost, SizeOfProductId = cartItem.SizeOfProductId};
                order.OrderItems.Add(orderItem);
            }
            order.OrderStatus = _unitOfWork.GetRepository<OrderStatus>().Find(1);
            orderRepo.Insert(order);
            _unitOfWork.SaveChanges();
            ClearCart();
            return View("Thanks");
        }
        #endregion

        #region Cart
        [HttpGet]
        public ActionResult Cart()
        {
            var currentUser = _unitOfWork.GetRepository<User>().GetAll()
                .Where(user => user.Email == User.Identity.Name).FirstOrDefault();
            var repo = _unitOfWork.GetRepository<Cart>().GetAll().ToList();
            Cart cart;
            if (repo.Where(t => t.User.ID == currentUser.ID).ToList().Count > 0) {
                cart = repo.Where(c => c.User.ID == currentUser.ID).FirstOrDefault();
                cart.CartItems = _unitOfWork.GetRepository<CartItem>().GetAll()
                    .Where(u => u.Cart.Id == cart.Id).ToList();
            }
            else{ 
                cart = new Cart(currentUser);
                _unitOfWork.GetRepository<Cart>().Insert(cart);
                _unitOfWork.SaveChanges();
            }
            return View(cart);
        }

        [HttpGet]
        public ActionResult AddToCart(int id)
        {
            var currentUser = _unitOfWork.GetRepository<User>().GetAll()
                .Where(user => user.Email == User.Identity.Name).FirstOrDefault();
            var shoe = _unitOfWork.GetRepository<Shoe>().Find(id);
            var repo = _unitOfWork.GetRepository<Cart>().GetAll().AsEnumerable();
            Cart cart;
            if (repo.Any(c => c.User.ID == currentUser.ID))
            {
                cart = repo.Where(c => c.User.ID == currentUser.ID).FirstOrDefault();
            }
            else
            {
                cart = new Cart(currentUser);
                _unitOfWork.GetRepository<Cart>().Insert(cart);
                _unitOfWork.SaveChanges();
            }
            cart.AddCartItem(shoe);
            _unitOfWork.SaveChanges();
            return RedirectToAction("Cart");
        }


        [HttpGet]
        public ActionResult RemoveCartProduct(int cartItemId)
        {
            var currentUser = _unitOfWork.GetRepository<User>().GetAll()
                .Where(user => user.Email == User.Identity.Name).FirstOrDefault();
            var cart = _unitOfWork.GetRepository<Cart>().GetAll().Where(t => t.User.ID == currentUser.ID).FirstOrDefault();
            var cartItem = _unitOfWork.GetRepository<CartItem>().Find(cartItemId);
            cart.CartItems.Remove(cartItem);
            _unitOfWork.GetRepository<Cart>().Update(cart);
            _unitOfWork.SaveChanges();
            return RedirectToAction("Cart");
        }

        [HttpGet]
        public ActionResult ClearCart()
        {
            var currentUser = _unitOfWork.GetRepository<User>().GetAll()
                .Where(user => user.Email == User.Identity.Name).FirstOrDefault();
            var cart = _unitOfWork.GetRepository<Cart>().GetAll().Where(t => t.User.ID == currentUser.ID).FirstOrDefault();
            cart.CartItems.Clear();
            _unitOfWork.SaveChanges();
            return RedirectToAction("Cart");
        }
        #endregion

    }
}

SiteOfClothing/Views/Catalog/Catalog.cshtml
@model IEnumerable<SiteOfShoes.Entities.Products.Product>

<!-- Section-->
<section class="py-5">
    <div class="text-center text-black">
        <h1 class="display-5 fw-bolder">Все товары</h1>
    </div>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (SiteOfShoes.Entities.Products.Product item in Model)
            {
<div class="col mb-5">
    <a class="text-decoration-none" href="@Url.Action("Product", "Product", new { id = item.Id })">
        <div class="card h-100">
            <!-- Sale badge-->
            @if (item.isSaled)
            {
<div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>}
            <!-- Product image-->
            <img class="card-img-top" src="@item.PhotoLink" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">@item.Name</h5>
                    <!-- Product price-->
                    @if (item.isSaled)
                    {
    <s>@item.Costs.Last().Cost</s> @(item.Costs.Last().Cost/100*(100-item.SalePercent)) <span>р.</span> }
else
{
@item.Costs.Last().Cost <span>р.</span>}
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="@Url.Action("AddToCart", "Ordering", new { id = item.Id })">В корзину</a></div>
            </div>
        </div>
    </a>
</div>      }
        </div>
    </div>
</section>

SiteOfClothing/Views/Catalog/ShoeCatalog.cshtml
@model SiteOfShoes.Entities.ProductTypes.Shoes.TypeOfShoe

<!-- Section-->
<section class="py-5">
    <div class="text-center text-black">
        <h1 class="display-5 fw-bolder">@Model.Name</h1>
    </div>
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (var item in Model.Shoes)
            {
<div class="col mb-5">
    <a class="text-decoration-none" href="@Url.Action("Product", "Product", new { id = item.Id })">
        <div class="card h-100">
            <!-- Sale badge-->
            @if (item.isSaled)
            {
<div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>}
            <!-- Product image-->
            <img class="card-img-top" src="@item.PhotoLink" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">@item.Name</h5>
                    <!-- Product price-->
                    @if (item.isSaled)
                    {
    <s>@item.Costs.Last().Cost</s> @(item.Costs.Last().Cost/100*(100-item.SalePercent)) <span>р.</span> }
else
{
@item.Costs.Last().Cost <span>р.</span>}
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="@Url.Action("AddToCart", "Ordering", new { id = item.Id })">В корзину</a></div>
            </div>
        </div>
    </a>
</div>      }
        </div>
    </div>
</section>

SiteOfClothing/Views/Catalog/ShoeTypes.cshtml
@model IEnumerable<SiteOfShoes.Entities.ProductTypes.Shoes.TypeOfShoe>

@foreach (var item in Model)
            {
                @Html.ActionLink(item.Name, "ShoeCatalog", "Catalog", new {type = item.Name} )
                <span>&nbsp;</span>
            }